### PR TITLE
Implement free response (FR) question type

### LINKED ISSUE #81: free response questions
Implement free response question type.

Will create an `answer` entry and a `vote` entry at vote time.

### PR DESCRIPTION
**Pull request by isaacdontjelindell**
Fixes #81.

This implements the free response question type.

When a free response question is encountered while a user is taking a survey:
- the user can enter and save an answer
- if the user changes their answer after saving once, the old answer is deleted from the database and the new answer is stored instead.

### CODE REVIEW

**Comment by etingel** [comment]
To fix: Check if currently entered text == last submitted FR. If so, turn it green again. Another way of doing this is to turn it green if we escape out of checkFR for that reason.

**Comment by etingel** [comment]
Also, the admin page won't automatically update with new FRs.

**Comment by etingel** [comment]
Since the admin page issue affects other parts of the system as well, I actually consider it to be outside the scope of the PR and should be spun up as a new issue.

With that visual fix in place, ACK.

**Comment by isaacdontjelindell** [comment]
re: updating results page, see #184.

**Pull request merged**
