### PR TITLE
Phonegap

### LINKED ISSUE #155: Mobile with PhoneGap
Add PhoneGap.

### PR DESCRIPTION
**Pull request by etingel**
Limitations discovered:

1) All assets have to be local. No more externally-linked libraries (include them directly, instead)
2) No more links based on root. So, no more doing 
a href="/?bah". Use a href="?bah" instead

Resolves #155

### CODE REVIEW

**Comment by isaacdontjelindell** [comment]
What's up with all the images being included? If they're part of Phonegap, should they be installed on a per-machine basis w/ npm rather than checking them into versioning?

**Comment by etingel** [comment]
Those are placeholder app icons.

**Comment by isaacdontjelindell** [comment]
Ah, gotcha. Do we need the  `.cordova/config.json` file if we aren't using any native device APIs? It seems like what you have checked in is just related to the hello world app.

Edit: Also, maybe use the minified FontAwesome css file rather than the bigger version - we're very unlikely to ever edit it anyway. Link to minified: http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css

**Comment by etingel** [comment]
Idk? I'll find out...

**Comment by etingel** [comment]
Must not have been too important...

**Comment by isaacdontjelindell** [comment]
Cool. I'm going to hold off merging this, a) to give Sarah a chance to review, and b) because I'm going to have to do a little work on the continuous integration scripts I've written on the server (I believe at least my script to deploy the webapp to GitHub pages hard-coded the `public` directory name).

**Comment by mcrosa01** [comment]
If I review this now, and let you/me merge it, can somebody explain the
scary parts to me on Tuesday? for example, why did you take away my fonts?

**Comment by isaacdontjelindell** [comment]
Sure. The fonts actually aren't gone, though - Erik just renamed the `public` folder to `www` to work better w/ PhoneGap.  If you look at the "Files Changed" tab at the top of this pull request, it'll say "File renamed without changes" under each of the font files (and any other files that were previously in `public`).

**Pull request merged**
