### PR TITLE
Db stubs issue 30

### LINKED ISSUE #30: Implement DB stubs
EOM.

### PR DESCRIPTION
**Pull request by isaacdontjelindell**
Closes #30.

This adds implementations of some of the database methods.

**Important Changes**
- This adds a dependency on the Q library, so make sure you run `npm install` after pulling.
- I refactored the `/vote` endpoint to require a `questionId` and an `answerId`. This is enough to identify a unique vote.
- `getResponses()` still is just a stub returning random data. It will be replaced with `getSurveyInfo()` (#38 and #39)
- The database schema is very different. You will probably want to `DROP TABLE test;`. See the [wiki](https://github.com/LutherSrProject/TapVote/wiki) for details on creating the new schema.

### CODE REVIEW

**Comment by isaacdontjelindell** [comment]
Please test this a little before merging - I didn't do a ton of testing so I'm sure there are bugs.

**Comment by etingel** [comment]
When we record a vote, we will (eventually) check the permissions of the survey, whether or not a vote is already recorded for the user for the question (ignored if multiple selections are allows by the question, so we check the question permissions, too), then we finally check if the user has already voted for this answer id.

So, we need to either provide the surveyId or gather that from the question and then load the row to determine permissions. We need to load the question row to determine the permissions of the question. We can check for a user's other answers to the question with the questionId (which is why it's nice that the questionId is stored with the vote, even though it doesn't have to be*).

*Storing the questionId with the vote means that it will be impractical to detach an existing answer to a given question - along with the votes for that answer - and attach it to a different question. That being said, I can't think of a single usecase for doing this, so it is completely acceptable.

Anyway, to the point: We will (eventually) need to load the survey row and the question row, regardless, so given that overhead we might as well do the secure thing and load the answer row as well. By loading the answer row, we can verify that the answerId exists and that the answer belongs to the given question. Then, the only data required by the api would be the answerId. surveyId and questionId can be optionally provided, but they would only be used as assertions that would throw an error if they don't match the db-provided values.

The recordVote code is fine for now, but I just wanted to explain this both for my sake and as an FYI.

As for what still needs to be done, it looks like it's good. I'll go ahead and merge it.

**Comment by isaacdontjelindell** [comment]
Do you think it makes sense to go ahead and make the `surveyId` a requirement for `/vote`, or should we just expect to get it from the `question` row? If you think we may want to include it in the request, we should add it now so that we don't have to include it later.

**Comment by etingel** [comment]
My thoughts are that it be an optional value that, if provided, must match the value determined by the database from the question row, otherwise throw an error. Eventually, the same should be done for questionId, but it's not that important right now since by the time the insert code block is reached, we would already have a db-provided questionId when that other code I described is added.

**Comment by isaacdontjelindell** [comment]
Gotcha, that makes good sense.

**Pull request merged**
