### PR TITLE
Simple database logging

### LINKED ISSUE #12: Log votes to database
Persist votes (A, B, C, D) into the database. The votes are currently being logged to the console.

### PR DESCRIPTION
**Pull request by isaacdontjelindell**
Initial stab at storing votes in a Postgres database (take a look at the main wiki page for some info on setting up a dev database). This resolves #12.

This adds some node modules to `package.json`, so make sure you run `sudo npm install` after pull in the changes.

I also took a stab at some error handling integration. It's still pretty primitive, but at least every error returns _some_ sort of HTTP error code (even if it's only `400 Bad Request`...).

At the point, the only way to see the votes currently in the database is to connect to it using `psql` and directly query the table:

```
$ sudo -u postgres psql tapvotetest
# SELECT * FROM test;
```

The next step will be to make a JSON controller/API endpoint that returns all the votes currently in the database.

### CODE REVIEW

**Comment by etingel** [comment]
Two things so far:

1) Is it standard practice to open a new database connection for each page load? Or does the pg library handle that by keeping the connection open for awhile and reusing it if it's needed?
2) Would it make sense to abstract the database stuff out to it's own file and pass it a callback?

For example, we would just leave something like this in requestHandlers:

``` javascript
db.saveVote(voteData /*this would be a dict of data that's needed to store the vote*/, function(err,errorName) {
    if (err) {
        errorResponse(response, errorName, err);
        return;
    }
    else {
        response.writeHead(200, {"Content-Type": "application/json"});
        response.write(postData); // echo back the postData for now
        response.end();
        console.log("[INFO] Logged vote " + data['vote'] + " to database.");
    }
});
```

**Comment by isaacdontjelindell** [comment]
1. According to the readme for the Postgres library I'm using (https://github.com/brianc/node-postgres), using pg.connect() utilizes a default/builtin connection pool. I didn't really dig into it but I'm assuming it's just working. I'm sure there's a way to configure it further (number of connections, etc).
2. I think you may be right about doing some abstraction of database stuff - it would save some boilerplate each time we need a DB connection. I'll try to work on that a bit today (I don't think I'm going to get to it till we meet this afternoon, but it shouldn't take too long.)

**Comment by etingel** [comment]
1. Looking at this further, everything makes sense. If another request comes in while we're waiting to hear back on the database call, it can make another connection and start the this call. Then, it can close the redundant connections after that is done. The connection pool probably intelligently decides whether or not to actually close the connection based on whether or not another request to the same server is in the pipeline. Therefor, ACK on using connect for each HTTP request (and maybe even each type of DB query that we have to do? idk...).
2. Not to mention, it would allow us to work in parallel. Just setup dummy functions that return example data and then I wouldn't have to wait on the database logic being done before using it at the server level. We would also avoid merge conflicts because we would be working in different files. No worries on the delay, I haven't had any time to work on this anyway.

**Comment by isaacdontjelindell** [comment]
Okay, I've done most of what we talked about in regards to abstracting the database stuff away. I'm not entirely satisfied with the way we're doing HTTP responses for error and success conditions, but I think that I'll wait to work on it until we have Express integrated (I'm imagining that Express will have a lot of utility functions to handle stuff like that).

If you're happy with this, go ahead and merge it.

**Comment by etingel** [comment]
Now that I've tested this, I have one quick question: how are we going to handle initializing the database? Realistically, we're only going to do it once per machine, so we could just do it by hand. But it would be nice to have that in the off chance that we release the code for this.

Other than that, ACK. I'll let you merge in case you decide to add initialization code. Doesn't matter to me, since all I really need is the command to type to create the table.

**Comment by isaacdontjelindell** [comment]
Not a bad idea - I've opened #22, and will work on something when I have a chance.

**Pull request merged**
