### PR TITLE
added question type labels to create, edit, and take survey

### PR DESCRIPTION
**Pull request by mcrosa01**

### CODE REVIEW

**Comment by isaacdontjelindell** [comment]
ack ack ack

**Comment by etingel** [comment]
NAK

Please refactor to use getTypeString() everywhere. That function should probably be defined globally. Isaac, where would be a good place for that?

**Comment by isaacdontjelindell** [comment]
@mcrosa01 You can put one copy of that getTypeString() code in `site.js`. This will allow you to use it everywhere else and avoid duplicating the code every time it's needed.

**Comment by mcrosa01** [comment]
Well, this should be muuuch better.

**Comment by isaacdontjelindell** [comment]
cool

**Pull request merged**
